FROM alpine:3.18

RUN apk get update &&\
	apk upgrade &&\
	apk add mysql mysql-client mariadb-server-utils &&\
	mkdir /run/mysqld &&\
	chown -R mysql:root /run/mysqld &&\
	rm -f /var/cache/apk/*

COPY /conf/mariadb-server.cnf /etc/my.cnf.d/mariadb-server.cnf
COPY /tools/script.sh /etc/my.cnf.d/script.sh

EXPOSE 3306

#ENTRYPOINT ["./etc/my.cnf.d/script.sh"]
