FROM alpine:3.18

RUN apk update &&\
	apk upgrade &&\
	apk add mysql mysql-client mariadb-server-utils &&\
	mkdir /run/mysqld &&\
	chown -R mysql:root /run/mysqld &&\
	chown -R mysql:mysql /var/lib/mysql &&\
	rm -f /var/cache/apk/* &&\
	rm -rf /etc/my.cnf.d/mariadb-server.cnf

COPY /conf/mariadb-server.cnf /etc/my.cnf.d/mariadb-server.cnf
COPY /tools/script.sh .

EXPOSE 3306

ENTRYPOINT ["./script.sh"]
