FROM alpine:3.18
RUN apk get update &&\
	apk upgrade &&\
	apk add curl &&\
	apk add php php-fpm php-mysqli php-gd \
	php-common php-curl php-phar php-cli \
	php-mbstring &&\
	apk add mariadb-client &&\
	apk add fcgi php-cgi

# RUN wget https://fr.wordpress.org/latest-fr_FR.zip -P /var/www &&\
# 	cd /var/www &&\
# 	unzip latest-fr_FR.zip  &&\
# 	rm latest-fr_FR.zip &&\
# 	chown -R root:root /var/www/wordpress

RUN mkdir -p /var/www/html
RUN adduser -D -S -G www-data www-data
RUN chmod 777 -R /var/www/html
RUN chown -R www-data:www-data /var/www/html

RUN curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar &&\
	chmod +x wp-cli.phar &&\
	mv -f wp-cli.phar /usr/local/bin/wp

COPY --chmod=777 /conf/www.conf /etc/php81/php-fpm.d/www.conf
COPY --chmod=777 /tools/auto_config.sh ./auto_config.sh

EXPOSE 9000

ENTRYPOINT ["./auto_config.sh"]
