FROM alpine:3.18

RUN apk get update &&\
	apk upgrade &&\
	apk add nginx &&\
	apk add openssl

RUN	mkdir -p /var/www/html &&\
	mkdir -p /etc/nginx/ssl &&\
	adduser -DSg www-data www-data &&\
	chmod 755 /var/www/html &&\
	chown -R www-data:www-data /var/www/html
	
RUN	openssl req -x509 -nodes -newkey rsa:2048 -keyout /etc/nginx/ssl/ssl.key -out /etc/nginx/ssl/ssl.crt -subj "/C=FR/ST=PB/L=PAYS-BASQUE/O=42/OU=42/CN=acomet.42.fr/UID=acomet"

COPY conf/nginx.conf etc/nginx/
COPY conf/default.conf etc/nginx/http.d/

EXPOSE 443

ENTRYPOINT ["chmod", "700", "etc/nginx/ssl"]
ENTRYPOINT ["nginx", "-g", "daemon off;"]
